replacers:
  - search: '/PC-(\d+)/g'
    replace: '[PC-$1](https://jira.ftscc.net/browse/PC-$1) '
  - search: '/ER-(\d+)/g'
    replace: '[ER-$1](https://jira.ftscc.net/browse/PC-$1) '
filter-by-commitish: true

template: |
  ## Whats changed
    
  $CHANGES
  
  ## Impact

  `What functionality is impacted with this release?  How does this change how a user uses the service?`
  
  ## Level of Risk 
   `normal`

  ## Tested?** 
   `yes`

  ## Screenshot of Fortify Scan Results

  `Include a screenshot of the results from the latest Fortify scan.  We should not be shipping anything that has critical or high issues (with some exceptions).`

  ## Expected Deployment Date  
   `some date in the near future`

  ## Deployment Plan

  `How are these changes rolled out?  Most of the time we can get by with the following line, but there might be additional work like config or database changes.  Try to be explicit if there are steps beyond a basic deployment.`

  Update version of service in deployment configurations and deploy.

  ## Backout Plan

  `How do we roll back these changes?  Most of the time we can get by with the following line, but that may not be sufficient if there were also config or database changes.  If there are, try to be explicit.`

  Should these changes need to be reverted, deploy the previous release of the service $PREVIOUS_TAG .
